- name: Install Python Flask dependency
  pip:
    name: {{item}}
    state: present
  with_items:
    - flask
    - flask-mysql

# Example git checkout from Ansible Playbooks
- name: Example git checkout from Ansible Playbooks
  git:
    repo: 'https://foosball.example.org/path/to/repo.git'
    dest: /srv/checkout
    version: release-0.22

# Example read-write git checkout from github
- name: Example read-write git checkout from github
  git:
    repo: ssh://git@github.com/mylogin/hello.git
    dest: /home/mylogin/hello

# And then add something that would start a service!
